name: kydrem_whatsapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.0.2
  asp: ^1.3.0
  result_dart: ^1.1.0
  stomp_dart_client: ^1.0.0
  http: ^1.1.0
  rxdart: ^0.27.7
  dio: ^5.3.2
  flavor: ^2.0.0
  form_builder_validators: ^9.1.0
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  loader_overlay: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
